twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
       pathImageArticles: '%path.images.article%'
       stripe_api_pk: '%stripe.api.pk%' 

when@test:
    twig:
        strict_variables: true
